//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ProCultura.CrossCutting.L10N {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class LocalizationKeys {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ProCultura.CrossCutting.L10N.LocalizationKeys", typeof(LocalizationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_AuthRequestNotRecognized.
        /// </summary>
        public static string message_AuthRequestNotRecognized {
            get {
                return ResourceManager.GetString("message_AuthRequestNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_DuplicateResource.
        /// </summary>
        public static string message_DuplicateResource {
            get {
                return ResourceManager.GetString("message_DuplicateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_EmailInUse.
        /// </summary>
        public static string message_EmailInUse {
            get {
                return ResourceManager.GetString("message_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_EmailIsRequired.
        /// </summary>
        public static string message_EmailIsRequired {
            get {
                return ResourceManager.GetString("message_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_EventAlreadyExist.
        /// </summary>
        public static string message_EventAlreadyExist {
            get {
                return ResourceManager.GetString("message_EventAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_EventNotFound.
        /// </summary>
        public static string message_EventNotFound {
            get {
                return ResourceManager.GetString("message_EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_InsufficientPrivileges.
        /// </summary>
        public static string message_InsufficientPrivileges {
            get {
                return ResourceManager.GetString("message_InsufficientPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_InvalidPassword.
        /// </summary>
        public static string message_InvalidPassword {
            get {
                return ResourceManager.GetString("message_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_LoginSuccess.
        /// </summary>
        public static string message_LoginSuccess {
            get {
                return ResourceManager.GetString("message_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_PasswordMismatch.
        /// </summary>
        public static string message_PasswordMismatch {
            get {
                return ResourceManager.GetString("message_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_RegistrationSuccess.
        /// </summary>
        public static string message_RegistrationSuccess {
            get {
                return ResourceManager.GetString("message_RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_ResourceNotFound.
        /// </summary>
        public static string message_ResourceNotFound {
            get {
                return ResourceManager.GetString("message_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UpdateUserSuccess.
        /// </summary>
        public static string message_UpdateUserSuccess {
            get {
                return ResourceManager.GetString("message_UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UserDeleted.
        /// </summary>
        public static string message_UserDeleted {
            get {
                return ResourceManager.GetString("message_UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UserNotFound.
        /// </summary>
        public static string message_UserNotFound {
            get {
                return ResourceManager.GetString("message_UserNotFound", resourceCulture);
            }
        }
    }
}
