//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCultura.CrossCutting.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCultura.CrossCutting.L10N.LocalizationKeys", typeof(LocalizationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_AuthRequestNotRecognized.
        /// </summary>
        public static string message_AuthRequestNotRecognized {
            get {
                return ResourceManager.GetString("message_AuthRequestNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_EmailInUse.
        /// </summary>
        public static string message_EmailInUse {
            get {
                return ResourceManager.GetString("message_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_InsufficientPrivileges.
        /// </summary>
        public static string message_InsufficientPrivileges {
            get {
                return ResourceManager.GetString("message_InsufficientPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_InvalidPassword.
        /// </summary>
        public static string message_InvalidPassword {
            get {
                return ResourceManager.GetString("message_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_LoginSuccess.
        /// </summary>
        public static string message_LoginSuccess {
            get {
                return ResourceManager.GetString("message_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_PasswordMismatch.
        /// </summary>
        public static string message_PasswordMismatch {
            get {
                return ResourceManager.GetString("message_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_RegistrationSuccess.
        /// </summary>
        public static string message_RegistrationSuccess {
            get {
                return ResourceManager.GetString("message_RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UpdateUserSuccess.
        /// </summary>
        public static string message_UpdateUserSuccess {
            get {
                return ResourceManager.GetString("message_UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UserDeleted.
        /// </summary>
        public static string message_UserDeleted {
            get {
                return ResourceManager.GetString("message_UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_UserNotFound.
        /// </summary>
        public static string message_UserNotFound {
            get {
                return ResourceManager.GetString("message_UserNotFound", resourceCulture);
            }
        }
    }
}
